/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaClinica;

import ControladorClinica.PersistenciaDoctor;
import ModeloClinica.Doctor;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author root
 */
public class ConsultarDoctores extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarDoctores
     */
    public ConsultarDoctores() {
        initComponents();
        Thread thread = new Thread(new Runnable() {
            Integer i=0;
            @Override
            public void run() {
                while(true){
                    try {
                        i = jTable1.getSelectedRow();
                        if(i>=0){
                            labelImagenPerfilDoctorP.setText("");
                            
                            labelImagenPerfilDoctorP.setIcon(new ImageIcon(PersistenciaDoctor.leerDoctor().get(i).getImagenPerfilDoctor().getImagen()));   
                        }    
                    }catch(Exception e ){if(i<=0)labelImagenPerfilDoctorP.setText("Selecciona una fila para ver su imagen de perfil");}
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        System.out.println("Error de thread en  " + ex.getMessage());
                    } 
                }
            }
        });
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelImagenPerfilDoctorP = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Piso", "Especialidad", "Doctor", "Contraseña", "NSS", "Turno"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Consultar Doctores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelImagenPerfilDoctorP.setText("Selecciona una fila para ver la imagen de perfil");

        jButton2.setText("Ventana Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(labelImagenPerfilDoctorP, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelImagenPerfilDoctorP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Integer tamano = PersistenciaDoctor.leerDoctor().size();
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[tamano] [4],
                    new String[]{
                       "Piso", "Especialidad", "Doctor", "Contraseña", "NSS", "Turno"
                    }
            ));
            Integer indice =0;
            for(Doctor d: PersistenciaDoctor.leerDoctor()){
                jTable1.setValueAt(d.getAreasDoctor().getAreaPiso(), indice, 0);
                jTable1.setValueAt(d.getAreasDoctor().getEspecialidadDoctor(), indice, 1);
                jTable1.setValueAt(d.getNombre(), indice, 2);
                jTable1.setValueAt(d.getPassword(), indice, 3);
                jTable1.setValueAt(d.getNumeroEmpleado(), indice, 4);
                jTable1.setValueAt(d.getAreasDoctor().getTurno(), indice, 5);
                indice +=1;
            }
        }catch(Exception e) {}
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new SesionRoot().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelImagenPerfilDoctorP;
    // End of variables declaration//GEN-END:variables
}
